### ISSUE TITLE
Build instructions are incomplete

### ISSUE THREAD

**Issue by jbulow** [Samuel-Tyler/fast_ber#11]
`cmake ../fast_ber
CMake Error at CMakeLists.txt:4 (add_subdirectory):
  The source directory

    /big/fast_ber/3rd_party/abseil-cpp

  does not contain a CMakeLists.txt file.
`

**Comment by jbulow** [comment]
The missing line is:

`git submodule update --init`

**Comment by Samuel-Tyler** [comment]
Thank you, added
