### ISSUE TITLE
syntax error when using nameless NULL

### ISSUE THREAD

**Issue by jbulow** [Samuel-Tyler/fast_ber#12]
In a asn1 file usually compiled with objective systems asn1 compiler there is:
```
someSeq ::= SEQUENCE
{
  NULL
}
```

fast_ber chokes in this:

```
syntax error, unexpected ASN_NULL, expecting COMPONENTS or ... or } or GENERIC_IDENTIFIER_LOWERCASE
```

asn1c also compiles this declaration fine.

**Comment by Samuel-Tyler** [comment]
Thank you very much for taking the time to submit a bug report!

Are you able to share your ASN.1 schema with me so I can resolve any other issues together?

Sam

**Comment by jbulow** [comment]
Unfortunately, the legal circumstances for the ASN.1 schema I used is a bit unclear. At the moment, the best I can do is to try out new versions of fast_ver on that schema file.

**Comment by Samuel-Tyler** [comment]
I've added support for anonymous sequence members:

https://github.com/Samuel-Tyler/fast_ber/commit/6f616f2e1e28657d571166789322da326efa372c

**Comment by Samuel-Tyler** [comment]
Please let me know if you encounter any other issues.
