### ISSUE TITLE
compile error with long long integers

### ISSUE THREAD

**Issue by cc9cii** [Samuel-Tyler/fast_ber#3]
Hello, I don't know for sure if this is an issue so apologies in advance in case this is an user error.  I'm evaluating various ASN.1 projects currently.  While trying out your compiler with a sample from my client I get an error with this line:

Integer64 ::= INTEGER (-9223372036854775808..9223372036854775807)

The error message from the compiler is:

Compilation error: stoll argument out of range

I'm using MSVC 15.9.14 (latest Community 2017)

**Comment by Samuel-Tyler** [comment]
Hi!

Thanks for your interest. I believe this is likely an issue as the full range of 64 bit ints should be supported.

Could you send me an ASN.1 file, so I can determine whether it would likely work with this compiler?

Thanks,
Sam

**Comment by cc9cii** [comment]
Sorry, the file contents can't be shared since it is under an NDA.  However, for testing, any asn.1 file can be modified to include a tag of above type Integer64.

**Comment by Samuel-Tyler** [comment]
I've resolved parsing of [int min
](718c405bbba93c9f284e310ea9ac9783dac7d04a) on the devel branch.

Thanks for your bug report.
