### ISSUE TITLE
Windows, visual studio build failure

### ISSUE THREAD

**Issue by mintyc** [Samuel-Tyler/fast_ber#5]
Vs 2017 latest has a few build errors, some with abseil and some in the main code. Nice to see you are continuing with this library. Paul

**Comment by Samuel-Tyler** [comment]
Thanks Paul, I will take a look at this

**Comment by Samuel-Tyler** [comment]
Hi Paul, 

Hope you are well.

I've added VS 2019 (passing) to [AppVeyor](https://ci.appveyor.com/project/Samuel-Tyler/fast-ber/builds/29226398).

Should work on your installation, but to save disk space I don't want to install multiple visual studio versions on my machine.

 Sam
