### ISSUE TITLE
Correctly parse SET in BER mode

### ISSUE THREAD

**Issue by Samuel-Tyler** [Samuel-Tyler/fast_ber#8]
Components of a SET may be arranged in any order. Currently parsing requires that they should be decoded in order. Correct this.

Elements in the SET may appear in any order. Duplicate items should be detected, causing a compilation failure. Lack of mandatory items should also be detected.

```
8.11Encoding of a set value8.11.1The encoding of a set value shall be constructed.8.11.2The contents octets shall consist of the complete encoding of a data value from each of the types listed in the ASN.1 definition of the set type, in an order chosen by the sender, unless the type was referenced with the keyword OPTIONALor the keyword DEFAULT.
The encoding of a data value may, but need not, be present for a type which was referenced with the keyword OPTIONALor the keyword DEFAULT.NOTE –The order of data values in a set value is not significant, and places no constraints on the orderduring transfer.
```

**Comment by benys** [comment]
Do you predict implement SETs?

**Comment by Samuel-Tyler** [comment]
Yes, it shouldn't be a big job I'll try to complete it this weekend

**Comment by benys** [comment]
Nice to hear you!

BTW your yacc grammar not work in bison (GNU Bison) 3.6.4. Should I create new Issue?

**Comment by Samuel-Tyler** [comment]
Yes, please, I have noticed this too. You can compile in release mode / set a CMake flag to avoid the generation in the meantime.
